
import type { Metadata } from "next";
import Navbar from "./components/Navbar";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function commonLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
         <html lang="en">
            <body className={`antialiased`}>
                <div className="max-w-6xl mx-auto">
                    <Navbar></Navbar>
                    {children}
                </div>
            </body>
        </html>

    );
}
